TABLE ACCOUNT{
    USER_NAME VARCHAR PK
    PASSWORD VARCHAR
}

TABLE USERS{
    USER_NAME VARCHAR    
    FULL_NAME NVARCHAR
    DOB LONG
    GENDER BOOLEAN
    MAIL VARCHAR
    PHONE VARCHAR
    CREATE_AT LONG
}

TABLE ROOMS{
    ROOM_CODE VARCHAR PK
    USER_NAME_OWNER VARCHAR
    -- PASS = # MEAN ROOM IS_DUAL
    PASSWORD VARCHAR
    -- TRUE MEAN IS_DUAL
    IS_DUAL BOOLEAN
    PRIVATE BOOLEAN
}

TABLE ROOM_MEMBER{
    ROOM_CODE VARCHAR 
    USER_NAME_MEMBER VARCHAR
    FOREIGN KEY (ROOM_CODE) REFERENCES ROOMS(ROOM_CODE)
}

TABLE INFO_ROOM{
    ROOM_CODE VARCHAR 
    ROOM_NAME NVARCHAR
}

TABLE CHAT_ROOMS_HISTORY{
    ROOM_CODE VARCHAR
    USER_NAME VARCHAR
    CONTENT NVARCHAR
    TIME LONG
}

TABLE LOG{
    EVENT VARCHAR
    CREATE_AT LONG
}
