-- DROP DATABASE HUCHAT;
CREATE DATABASE HUCHAT;
USE HUCHAT;

CREATE TABLE USERS(
    USER_NAME VARCHAR(20) PRIMARY KEY,    
    FULL_NAME NVARCHAR(100),
    DOB LONG,
    GENDER BOOLEAN,
    MAIL VARCHAR(50),
    CREATE_AT LONG
);

CREATE TABLE ACCOUNT(
    USER_NAME VARCHAR(20) PRIMARY KEY,
    PASSWORD VARCHAR(64)
);

CREATE TABLE GROUPS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_OWNER VARCHAR(15),
    PASSWORD VARCHAR(64)
);

CREATE TABLE INFO_GROUP(
  ID INT, 
  NAME_GROUP NVARCHAR(50),
  ID_OWNER VARCHAR(15),
  PASSWORD VARCHAR(64)
);
CREATE TABLE LOG(
    EVENT VARCHAR(100),
    CREATE_AT LONG
)
DELIMITER $$
CREATE PROCEDURE PROC_INSERT_ACCOUNT (
	IN USER_NAME VARCHAR(20),  
	IN PASSWORD VARCHAR(64))
BEGIN
    INSERT INTO ACCOUNT VALUES(USER_NAME, PASSWORD);
END; $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE PROC_CHANGE_PASSWORD_ACCOUNT (
	IN N_USER_NAME VARCHAR(20),  
	IN N_PASSWORD VARCHAR(64))
BEGIN
    UPDATE ACCOUNT 
    SET PASSWORD = N_PASSWORD 
    WHERE ACCOUNT.USER_NAME = N_USER_NAME;
END; $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE PROC_DELETE_ACCOUNT (
	IN N_USER_NAME VARCHAR(20))
BEGIN
    DELETE FROM ACCOUNT 
    WHERE USER_NAME = N_USER_NAME;
END; $$
DELIMITER ;

-- CALL PROC_DELETE_ACCOUNT("MON");
-- CALL PROC_CHANGE_PASSWORD_ACCOUNT ("MON", "YEYEYE");
-- CALL PROC_INSERT_ACCOUNT ("MON","XXX");
-- INSERT INTO `ACCOUNT` VALUES ("LONG", "DAS");
-- SELECT * FROM `group` 
-- System.currentTimeMillis()
