DROP DATABASE IF EXISTS HUCHAT;
CREATE DATABASE HUCHAT;
USE HUCHAT;

CREATE TABLE ACCOUNT(
    USER_NAME VARCHAR(20) PRIMARY KEY,
    PASSWORD VARCHAR(64)
);

CREATE TABLE USERS(
    USER_NAME VARCHAR(20) NOT NULL,    
    FULL_NAME NVARCHAR(100),
    DOB LONG,
    GENDER BOOLEAN,
    MAIL VARCHAR(50),
    PHONE VARCHAR(11),
    CREATE_AT LONG,
    AVATAR_PATH VARCHAR(200),
    FOREIGN KEY (USER_NAME) REFERENCES ACCOUNT(USER_NAME)
) ENGINE = INNODB;

CREATE TABLE ROOMS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_NAME_OWNER VARCHAR(15) NOT NULL,
    PASSWORD VARCHAR(64),
    FOREIGN KEY (USER_NAME_OWNER) REFERENCES ACCOUNT(USER_NAME)
)ENGINE = INNODB;

CREATE TABLE ROOM_MEMBER(
    ID INT NOT NULL, 
    USER_NAME_MEMBER VARCHAR(20),
    FOREIGN KEY (ID) REFERENCES ROOMS(ID),
    FOREIGN KEY (USER_NAME_MEMBER) REFERENCES ACCOUNT(USER_NAME)
)ENGINE = INNODB;

CREATE TABLE INFO_ROOM(
    ID INT NOT NULL, 
    NAME_ROOM NVARCHAR(50),
    AVATAR_PATH VARCHAR(200),
    FOREIGN KEY (ID) REFERENCES ROOMS(ID)
)ENGINE = INNODB;

CREATE TABLE CHAT_ROOMS_HISTORY(
    ID_ROOM INT NOT NULL,
    USER_NAME VARCHAR(20),
    CONTENT NVARCHAR(1000),
    TIME LONG
);

CREATE TABLE LOG(
    EVENT VARCHAR(100),
    CREATE_AT LONG
);

-------------------------------------LOG-------------------------------------------
DELIMITER $$
CREATE PROCEDURE PROC_INSERT_LOG_EVENT (
    IN ACTION VARCHAR(100))
BEGIN
	INSERT INTO LOG VALUES(ACTION, UNIX_TIMESTAMP(now()));
END; $$
DELIMITER ;

-- call PROC_INSERT_LOG_EVENT("aaaaaaaa");

DELIMITER $$
CREATE PROCEDURE PROC_VIEW_ALL_EVENT ()    
BEGIN
    SELECT EVENT AS "Hành động", FROM_UNIXTIME(CREATE_AT, "%d-%m-%Y %H:%i:%s") AS "Thời gian tạo"
    FROM LOG
    ORDER BY CREATE_AT DESC;
END; $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE PROC_VIEW_EVENT_BETWEEN (
    IN TIME_A LONG,
    IN TIME_B LONG
)    
BEGIN
    SELECT EVENT AS "Hành động", FROM_UNIXTIME(CREATE_AT, "%d-%m-%Y %H:%i:%s") AS "Thời gian tạo"
    FROM LOG
    WHERE TIME_A <= CREATE_AT AND CREATE_AT <= TIME_B
    ORDER BY CREATE_AT DESC;
END; $$
DELIMITER ;
-- SELECT FROM_UNIXTIME(UNIX_TIMESTAMP(now()), "%d-%m-%Y %H:%i:%s");
-------------------------------------LOG-------------------------------------------

------------------------------------LOGIN------------------------------------------
DELIMITER $$
CREATE PROCEDURE PROC_LOGIN_EVENT (
    IN USER_NAME VARCHAR(20))
BEGIN
	SET USER_NAME = CONCAT("LOGIN WITH USER NAME ", USER_NAME);
	CALL PROC_INSERT_LOG_EVENT(USER_NAME);
END; $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE PROC_LOGOUT_EVENT (
    IN USER_NAME VARCHAR(20))
BEGIN
	SET USER_NAME = CONCAT("LOGOUT WITH USER NAME ", USER_NAME);
	CALL PROC_INSERT_LOG_EVENT(USER_NAME);
END; $$
DELIMITER ;

------------------------------------LOGIN------------------------------------------

-----------------------------------ACCOUNT-----------------------------------------
DELIMITER $$
CREATE PROCEDURE PROC_INSERT_ACCOUNT (
	IN N_USER_NAME VARCHAR(20),  
	IN PASSWORD VARCHAR(64))
BEGIN
    INSERT INTO ACCOUNT VALUES(N_USER_NAME, PASSWORD);
    INSERT INTO USERS(USER_NAME) VALUES(N_USER_NAME);
END; $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE PROC_CHANGE_PASSWORD_ACCOUNT (
	IN N_USER_NAME VARCHAR(20),  
	IN N_PASSWORD VARCHAR(64))
BEGIN
    UPDATE ACCOUNT 
    SET PASSWORD = N_PASSWORD 
    WHERE ACCOUNT.USER_NAME = N_USER_NAME;
END; $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE PROC_DELETE_ACCOUNT (
	IN N_USER_NAME VARCHAR(20))
BEGIN
    DELETE FROM USERS 
    WHERE USER_NAME = N_USER_NAME;
    DELETE FROM ACCOUNT 
    WHERE USER_NAME = N_USER_NAME;
END; $$
DELIMITER ;
-----------------------------------ACCOUNT-----------------------------------------

---------------------------------INFO_USERS----------------------------------------

DELIMITER $$
CREATE PROCEDURE PROC_UPDATE_INFO_USER (
	IN N_USER_NAME VARCHAR(20),  
    IN N_FULL_NAME NVARCHAR(100),
    IN N_DOB LONG,
    IN N_GENDER BOOLEAN,
    IN N_MAIL VARCHAR(50),
    IN N_PHONE VARCHAR(11),
    IN N_CREATE_AT LONG,
    IN N_AVATAR_PATH VARCHAR(200))
BEGIN
    UPDATE USERS 
    SET FULL_NAME = N_FULL_NAME,
        DOB = N_DOB,
        GENDER = N_GENDER,
        MAIL = N_MAIL,
        PHONE = N_PHONE,
        CREATE_AT = N_CREATE_AT,
        AVATAR_PATH = N_AVATAR_PATH
    WHERE USERS_NAME = N_USER_NAME;
END; $$
DELIMITER ;
-- -------------------------------INFO_USERS----------------------------------------

-- --------------------------------TRIGGER-----------------------------------------
-- INSERT
--

-- ---------------------------------TRIGGER-----------------------------------------
-- CALL PROC_DELETE_ACCOUNT("MON");
-- CALL PROC_CHANGE_PASSWORD_ACCOUNT ("MON", "YEYEYE");
-- CALL PROC_INSERT_ACCOUNT ("tttt","XXX");
-- INSERT INTO `ACCOUNT` VALUES ("LONG", "DAS");
-- SELECT * FROM `group` 
-- System.currentTimeMillis()
DELETE  FROM `ACCOUNT` WHERE PASSWORD = "XXX";